# Dependencies
markdown:         kramdown
highlighter:      Rouge

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Brian Zhao
tagline:          'Computational Chemistry Student'
description:      'Third-year computational chemistry student at the University of Cambridge.'

author:
  name:           'Brian Zhao'

paginate:         5
plugins:
  - jekyll-paginate
  - jekyll-gist


# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/brianz98
